### ISSUE TITLE
How did you fix webview?

### ISSUE THREAD

**Issue by mark-hahn** [gstack/atom-browser-webview#1]
I assumed Atom always did a `display:none`.  This is great.  I've got a bunch of features that have been waiting on this.

BTW, I'd happily accept a PR.  No reason to confuse everyone with two packages.

**Comment by lynchpin4** [comment]
fix: floating it over the div and hiding it via visibility / offscreen fixed-level positioning. didnt have time for a proper pull request but i'm fine w/ that.. the number of browser packages in the repo astounded me (given that none of them work) - so i jumped at the opportunity of a rename on the chance people would follow with more (newer) downloads.

there's still stuff to do in this package, bugs i still see coming up. that said i looked at your repos list - you do work on some absolutely commendable stuff w/ atom. i have more ideas that would probably interest you in that vein (https://github.com/mark-hahn/html-tab - fix for this being 1 of them) - are you interested in setting up a collaborative gh organization for work like this between a small team? email me, stack@ruleless.org

**Comment by mark-hahn** [comment]
That is a creative fix.  Tracking the panes and items sounds like a pain
though.  Whatever works
 is fine and it is only temporary until the webview bug is fixed.  BTW, I
just got a notice from the chrome folks that a webview bug was fixed.  I
hope it is this bug.

>  on the chance people would follow with more (newer) downloads.

I was getting 15 downloads a day for months until recently.  I would assume
with this fix that it would pick up again.

> are you interested in setting up a collaborative gh organization

I am not sure what you mean.  Do you just mean collaborating on a normal
project or something like a company?  Maybe you could point me to an
example.

It would be great to have some help.  I've gotten carried away publishing
16 packages and I can't support them all myself.  Of course half of them
may not be worth the trouble to support.

Speaking of packages I'm about half-done with a node IDE.  It is a
source-based debugger integrated with Atom to debug any node process
including Atom editor windows.  If I'm not mistaken it will surpass the
capabilities of anything like eclipse on node.

Once again Atom provides an excellent foundation.

**Comment by lynchpin4** [comment]
Yea, basically I have another coder here (my roommate) who I've known for years and basically taught javascript. What I figured is, creating a GH organization not unlike what Atom uses (basically provides functionality similar to an account which can be managed by multiple users) - Like you said it would be great to have some help going around maintaining packages / adding creative input.

The solution here, while it's not ideal - I've been thinking for awhile of encapsulating it into a small JS module for various libraries that require a similar solution, + implementation of dom environment (CSS) independent pane managers (resize/layout) for atom and other webapps.

> Speaking of packages I'm about half-done with a node IDE.  It is a
> source-based debugger integrated with Atom to debug any node process
> including Atom editor windows.  If I'm not mistaken it will surpass the
> capabilities of anything like eclipse on node.

Fresh, I've shared the same idea and I'd love to help ya out (Atom REALLY needs some build/debug process functionality..) - I do C++/C#/JS primarily and I've used all the major scripting languages over the years so I got a lot of relevant experience to apply in developing that sort of thing.

Do you use Skype or any other IM stuff at all? maybe we could discuss this further there.

Cheers,
- gs

**Comment by mark-hahn** [comment]
>  What I figured is, creating a GH organization not unlike what Atom uses

That sounds interesting.  We could try it out with a couple of my old
packages and some new ones.  We could pitch it on the forum to try to get
some more collaborators.  The only catch I can think of is leadership.  An
organization by definition needs someone to settle arguments etc.  Maybe
each project could have a BDFL with the emphasis on the B.

>  encapsulating it into a small JS module for various libraries that
> require a similar solution

That would be nice.  We could start by bringing the existing html-tab up to
date and flesh it out a bit.  However, making a tool for others to use is
tricky.  It is hard to predict what they really need.

Re: The IDE.  I had a lot working, pretty much everything other than
viewing variables.  Then I ran into this shadow-dom stuff and I've been
stuck for a while.  As soon as I get past this problem I'll document the
IDE a tiny bit and you can take a look.  You can download it now at
node-ide but you'll find it quite broken.

> Do you use Skype or any other IM stuff at all?

Not really but I love to type long emails (grin).  Us old guys like email.
I would look forward to discussing this stuff.  Do you hang out at the
forum?  I have a big presence there.  In any case we should switch this
discussion to email.  I'm at mark@hahnca.com.

P.S. I'm going to be buried in the IDE for a week or two more.  You may
have to be the one to set any organization up.
