### ISSUE TITLE
Why this is cloned and uploaded as your own , instead of a fork?

### ISSUE THREAD

**Issue by v3ss0n** [gstack/atom-browser-webview#14]
You are splitting the community in half without reason.
You can just do a fork-on-github and submit pull request to Main Developer , at https://github.com/mark-hahn/web-browser .

That way both synced and it works great for both developers and users.

**Comment by aidanamavi** [comment]
:+1: to your comment @v3ss0n

**Comment by lynchpin4** [comment]
original package wasn't switching to webview tags but there are others now so i unpublished.

y'all are free
