### ISSUE TITLE
Add X-Frame-Options bypass to feature list of this Package  (i.e README.md)

### ISSUE THREAD

**Issue by DinisCruz** [gstack/atom-browser-webview#2]
This package solves a very common problem when embedding web pages inside web-based environments (like Atom or node-webkit) which is the need to disable the X-Frame-Options header (designed for IFrame/ClickJacking security protection). 

The fact that that works, is a good reason to install it

You can see an example of the problem here https://github.com/mark-hahn/web-browser/issues/5#issuecomment-69447641 (on a similar package) 

And here is the image that shows the harder case (GitHub)

![image](https://cloud.githubusercontent.com/assets/656739/5690827/d7568882-989d-11e4-84a0-716bc772c7de.png)

Nice work and thanks for publishing this package

**Comment by lynchpin4** [comment]
added
"Is an actual web browser, no use of iframes so every site should load as it would in Chrome or Firefox. (Some individual web features i.e. popups may not be supported) *"

to the readme.md - otherwise closing this b/c not an issue. thanks for testing!
