### ISSUE TITLE
Fixed height size

### ISSUE THREAD

**Issue by imarinic** [gstack/atom-browser-webview#32]
I find Atom editor very useful, and I really like the possibility of having web browser integrated in the Editor, but I am having some problems with web browser. At first, after installing browser, everything worked fine, but after few days the size of the browser itself decreased. To be precise, height of the browser (regardless of position and size of the pane) became fixed on some value, without the possibility to extend it (please see screenshot). After reinstallation of the Atom it worked fine for a day or two, and then the height "shrank" again. Do you have any suggestions how to fix it?

![atom](https://cloud.githubusercontent.com/assets/20886218/18223475/829e20fc-71b8-11e6-8275-23fa12eeb0dd.jpg)

**Comment by msgfxeg** [comment]
I have the same problem :(

**Comment by imarinic** [comment]
Fortunately, the issue is solved, as explained by s4s0l in Issue #31, simply by adding
webview {
height: 100%;
}
to styles.less.

thanx to  s4s0l
