### ISSUE TITLE
You can close issue #1

### ISSUE THREAD

**Issue by mark-hahn** [gstack/atom-browser-webview#5]
The `web-browser` package has updated to 1.0.0 and now uses the `webview` tag instead of the `iFrame` tag.

**Comment by mark-hahn** [comment]
Why is that issue locked? You are blocking me from closing my own issue which is strange to say the least..

**Comment by mark-hahn** [comment]
I'm guessing you want issue #1 to stay there so people who see it will think `web-browser` still has a problem and I am still endorsing your package to fix it.  If this is true then it is a dick move.  Such lack of professionalism will get you nowhere.

**Comment by lynchpin4** [comment]
i'm not super used to using github, so my bad. i'll unlock that issue. sorry

**Comment by lynchpin4** [comment]
actually wasn't locked, dunno why you couldn't reply

**Comment by mark-hahn** [comment]
Sorry I accused you of nefariousness. It is locked for anyone other than you.  Just close that issue and this one.

This is what it looks like when I open it.

![urfdkdkhgd](https://cloud.githubusercontent.com/assets/811455/6217884/6a8233c6-b5cd-11e4-8c49-a48361b3119c.gif)

**Comment by mark-hahn** [comment]
You obviously know how to click the Close button and you won't.  I've reported your project as malicious.
